name: isogram
version: 1.7.0.8

dependencies:
  - base

library:
  exposed-modules: Isogram
  source-dirs: src
  ghc-options: -Wall
  dependencies:
   - containers 
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isogram
      - hspec
